# Generated by Django 4.1.5 on 2023-01-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_managers_users_date_joined_users_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="age",
            field=models.SmallIntegerField(null=True),
        ),
    ]
