# Generated by Django 4.1.5 on 2023-01-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_users_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "member"),
                    ("moderator", "moderator"),
                    ("admin", "admin"),
                ],
                default="member",
                max_length=9,
            ),
        ),
    ]
