# Generated by Django 4.1.6 on 2023-02-19 13:23

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_users_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, validators=[users.validators.check_birth_date]
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Регистрация с домена 'rambler.ru' запрещена",
                        regex="@rambler.ru",
                    )
                ],
            ),
        ),
    ]
