# Generated by Django 4.1.6 on 2023-02-19 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_users_birth_date_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Регистрация с домена 'rambler.ru' запрещена",
                        regex="@rambler.ru",
                    )
                ],
            ),
        ),
    ]
