# Generated by Django 4.1.6 on 2023-02-19 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=10,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
